# Generated by Django 5.0 on 2023-12-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_products_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_executed',
            field=models.BooleanField(default=False),
        ),
    ]
